# """
# Django settings for base project.

# Generated by 'django-admin startproject' using Django 4.2.23.

# For more information on this file, see
# https://docs.djangoproject.com/en/4.2/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/4.2/ref/settings/
# """
# import os
# from pathlib import Path
# from datetime import timedelta

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent


# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-$t4$hx78_j=x^nbczm3_o-@j&e8a6!&7ef(n#&n7oop1#!es*9'

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

# ALLOWED_HOSTS = ["*", "localhost", "http://localhost:5173", '192.168.42.212', "127.0.0.1"]

# # В файле settings.py добавьте:
# AUTH_USER_MODEL = 'store.CustomUser'

# FRONTEND_URL = 'http://localhost:5173'


# # settings.py
# # Укажите здесь IP вашего компьютера в локальной сети
# BACKEND_URL = "http://192.168.42.212:8000"


# from celery.schedules import crontab

# CELERY_BEAT_SCHEDULE = {
#     'clear-old-files-daily': {
#         'task': 'chat.tasks.delete_old_files_task',
#         'schedule': crontab(hour=3, minute=0), # Каждый день в 03:00
#     },
# }



# STORY_VIDEO_MAX_SIZE_MB = 50
# STORY_VIDEO_MAX_DURATION = 30



# REST_FRAMEWORK = {
#     'DEFAULT_THROTTLE_RATES':{
#         'resend_activation':'5/hour',
#     },
#     'DEFAULT_AUTHENTICATION_CLASSES':(
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
        
#     ),
#     'DEFAULT_FILTER_BACKENDS':[
#         'rest_framework.filters.SearchFilter',
#     ]
# }

 


# SIMPLE_JWT = {
#     'ACCESS_TOKEN_LIFETIME': timedelta(minutes=500), 
#     'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'AUTH_HEADER_TYPES': ('Bearer',),
# }




# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'push_notifications',
#     'rest_framework',
#     'rest_framework_simplejwt.token_blacklist',
#     'django_filters',
#     'store', 
#     'corsheaders',
#     'channels'
   
# ]

# CHANNEL_LAYERS ={
#     'default':{
#         'BACKEND':"channels_redis.core.RedisChannelLayer",
#         "CONFIG": {
#             "hosts":[("127.0.0.1", 6379)],
#         }
#     }
# }

# MIDDLEWARE = [
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
# ]

# ROOT_URLCONF = 'base.urls'
# # CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:5173',
#     'http://localhost:5173',
# ]

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "redis://127.0.0.1:6379/1",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }



# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

# ASGI_APPLICATION = 'base.asgi.application'


# # Database
# # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'storeprice_db',
#         'USER': 'postgres',
#         'PASSWORD': 'root',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# STATIC_URL = 'static/'


# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# # URL брокера (Redis запущен локально)
# CELERY_BROKER_URL = 'redis://localhost:6379/0'
# # Где хранить результаты выполнения задач
# CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

# # Настройки времени и формата
# CELERY_ACCEPT_CONTENT = ['json']
# CELERY_TASK_SERIALIZER = 'json'
# CELERY_RESULT_SERIALIZER = 'json'
# CELERY_TIMEZONE = 'UTC' # Или твой часовой пояс




















# для реального сервера




"""
Django settings for base project.
Generated by 'django-admin startproject' using Django 4.2.23.
"""
import os
from pathlib import Path
from datetime import timedelta
import dj_database_url  # 🔥 ДОБАВЛЕН ИМПОРТ ДЛЯ RENDER

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'



MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 🔥 Проверяем, находимся ли мы на сервере Render
if 'RENDER' in os.environ:
    # ⚠️ ВАЖНО: Замени '/var/data' на ТОТ САМЫЙ путь, который написан у тебя в Mount path в панели Render!
    # Добавляем /media в конце, чтобы внутри диска была аккуратная папка
    MEDIA_ROOT = '/var/data/media' 
else:
    # Для локальной разработки на твоем компьютере всё остается по-старому
    MEDIA_ROOT = BASE_DIR / 'media'

# SECRET_KEY = 'django-insecure-$t4$hx78_j=x^nbczm3_o-@j&e8a6!&7ef(n#&n7oop1#!es*9'

# Замени свою строку на эту:
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-$t4$hx78_j=x^nbczm3_o-@j&e8a6!&7ef(n#&n7oop1#!es*9')

# Включаем DEBUG, если мы не на реальном сервере
DEBUG = os.environ.get('RENDER') is None

# 🔥 УМНЫЕ ХОСТЫ: Разрешаем Render подключаться к нашему приложению
ALLOWED_HOSTS = ["*", "localhost", "http://localhost:5173", '10.192.85.180', "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "https://nextstore-iumj.onrender.com",
]

# Указываем Django, что мы находимся за HTTPS-прокси (Render)
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

AUTH_USER_MODEL = 'store.CustomUser'
FRONTEND_URL = 'http://localhost:5173'
BACKEND_URL = "http://10.192.85.180:8000"

from celery.schedules import crontab
CELERY_BEAT_SCHEDULE = {
    'clear-old-files-daily': {
        'task': 'chat.tasks.delete_old_files_task',
        'schedule': crontab(hour=3, minute=0), # Каждый день в 03:00
    },
}

STORY_VIDEO_MAX_SIZE_MB = 50
STORY_VIDEO_MAX_DURATION = 30

REST_FRAMEWORK = {
    'DEFAULT_THROTTLE_RATES':{
        'resend_activation':'5/hour',
    },
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS':[
        'rest_framework.filters.SearchFilter',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=300),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS':True,
    'BLACKLIST_AFTER_ROTATION':True,
    'AUTH_HEADER_TYPES':('Bearer',),
}

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'push_notifications',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',
    'store', 
    'corsheaders',
    'channels'
]

# 🔥 УМНЫЙ REDIS (Берет ссылку из Render или использует локальный)
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379')

CHANNEL_LAYERS ={
    'default':{
        'BACKEND':"channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts":[REDIS_URL],
        }
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # 🔥 ДОБАВЛЕНО ДЛЯ СТАТИКИ НА RENDER
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'base.urls'

# Для тестов мобильного приложения лучше временно разрешить все источники
CORS_ALLOW_ALL_ORIGINS = True

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL, # 🔥 Используем единый Redis URL
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'base.asgi.application'

# 🔥 УМНАЯ БАЗА ДАННЫХ
# Если на Render есть переменная DATABASE_URL, используем её. Иначе - твой локальный Postgres.
if os.environ.get('DATABASE_URL'):
    DATABASES = {
        'default': dj_database_url.config(default=os.environ.get('DATABASE_URL'), conn_max_age=600)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'storeprice_db',
            'USER': 'postgres',
            'PASSWORD': 'root',
            'HOST': 'localhost',
            'PORT': '5432',
        }
    }

STATIC_URL = 'static/'
# 🔥 НАСТРОЙКИ СТАТИКИ ДЛЯ RENDER
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'


# 🔥 НАСТРОЙКИ РЕАЛЬНОЙ ОТПРАВКИ ПОЧТЫ
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')  # или smtp.yandex.ru / smtp.gmail.com
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 465))
EMAIL_USE_SSL = True  # Для порта 465 используем True. Если порт 587, то EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'aleksskayivanov@gmail.com')

# Переменная приложения-пароля (не обычный пароль от почты, а сгенерированный в настройках безопасности)
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'azcuofdkndboxljx')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER



# 🔥 УМНЫЙ CELERY
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'