# Generated by Django 4.2.23 on 2025-07-17 07:32

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='One',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOne', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameRegions', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SelectionObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameObject', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeUserName', models.CharField(max_length=100)),
                ('priceUser', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productNameUser', models.CharField(max_length=100)),
                ('addressUserStore', models.ImageField(blank=True, null=True, upload_to='user_images/')),
                ('dateUpdateUser', models.DateField(blank=True, null=True)),
                ('fk_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('regionUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.regions')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameStoreAdmin', models.CharField(max_length=100)),
                ('priceAdmin', models.DecimalField(decimal_places=2, max_digits=10)),
                ('addressProductAdmin', models.CharField(max_length=100)),
                ('imageProductAdmin', models.ImageField(upload_to='store_images')),
                ('nameProductAdmin', models.CharField(max_length=100)),
                ('dateUpdateAdmin', models.DateField(blank=True, null=True)),
                ('weightProductAdmin', models.CharField(blank=True, max_length=50, null=True)),
                ('fk_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('regionProductAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.regions')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFeature', models.CharField(max_length=100)),
                ('valueFeature', models.CharField(max_length=255)),
                ('fk_Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.users')),
            ],
        ),
        migrations.CreateModel(
            name='FeatureStoreAdmins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFeature', models.CharField(max_length=100)),
                ('valueFeatur', models.CharField(max_length=100)),
                ('fk_StoreAdmins', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature', to='store.storeadmins')),
            ],
        ),
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=100)),
                ('loginAdmin', models.CharField(max_length=100)),
                ('mailAdmin', models.CharField(max_length=100)),
                ('passwordAdmin', models.CharField(max_length=100)),
                ('fk_StoreAdmin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.storeadmins')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
