# Generated by Django 4.2.23 on 2025-07-17 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admins',
            options={'verbose_name': 'Admin', 'verbose_name_plural': 'Admins'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='featurestoreadmins',
            options={'verbose_name': 'FeatureStoreAdmin', 'verbose_name_plural': 'FeatureStoreAdmins'},
        ),
        migrations.AlterModelOptions(
            name='featureusers',
            options={'verbose_name': 'FeatureUser', 'verbose_name_plural': 'FeatureUsers'},
        ),
        migrations.AlterModelOptions(
            name='regions',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='selectionobject',
            options={'verbose_name': 'SelectionObject', 'verbose_name_plural': 'SelectionObjects'},
        ),
        migrations.AlterModelOptions(
            name='storeadmins',
            options={'verbose_name': 'FeatureStoreAdmin', 'verbose_name_plural': 'FeatureStoreAdmins'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='users',
            name='imageUserStore',
            field=models.ImageField(blank=True, null=True, upload_to='user_images/'),
        ),
        migrations.AlterField(
            model_name='users',
            name='addressUserStore',
            field=models.CharField(default='ул Кадырова', max_length=100),
            preserve_default=False,
        ),
    ]
