# Generated by Django 4.2.23 on 2025-07-19 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='date_update',
            new_name='dateUpdate',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='productName',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_type',
            new_name='productType',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='store_name',
            new_name='storeName',
        ),
    ]
