# Generated by Django 4.2.23 on 2026-01-20 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_messageregionchat_messageregionfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageregionfile',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messageregionfile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='region/messages/thumbnails/'),
        ),
        migrations.AddField(
            model_name='messageregionfile',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='messageregionchat',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_messages', to='store.regions'),
        ),
    ]
