# Generated by Django 4.2.23 on 2025-07-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_admins_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeadmins',
            name='dateUpdateAdmin',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='dateUpdateUser',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
