# Generated by Django 4.2.23 on 2025-07-22 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_owner_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('owner', 'Owner'), ('user', 'User')], max_length=10),
        ),
    ]
