# Generated by Django 4.2.23 on 2026-01-26 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_messagefile_delete_messageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='store.privatemessage'),
        ),
    ]
