# Generated by Django 4.2.23 on 2026-03-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_privatemessage_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessagefile',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatemessagefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='private_chat/'),
        ),
        migrations.AlterField(
            model_name='privatemessagefile',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], max_length=20),
        ),
    ]
