# Generated by Django 4.2.23 on 2026-03-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_privatemessagefile_is_downloaded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessagefile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='private_chat/thumbnails/'),
        ),
    ]
