# Generated by Django 4.2.23 on 2025-07-24 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_product_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productType',
            new_name='productUser',
        ),
    ]
