# Generated by Django 4.2.23 on 2026-04-07 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_privatemessagefile_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessagefile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='groups/messages/thumbnails/'),
        ),
    ]
