# Generated by Django 4.2.23 on 2026-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_groupmessagefile_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='image',
        ),
        migrations.AddField(
            model_name='messagefile',
            name='is_downloaded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagefile',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='messages/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='messages/files/'),
        ),
        migrations.AlterField(
            model_name='messagefile',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], max_length=20),
        ),
    ]
