# Generated by Django 4.2.23 on 2026-07-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_customuser_is_open_customuser_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessagefile',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='privatemessagefile',
            name='type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('document', 'Document')], max_length=20),
        ),
    ]
