# Generated by Django 4.2.23 on 2026-08-11 17:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_groupmessagefile_file_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageregionchat',
            name='is_read',
        ),
        migrations.AddField(
            model_name='messageregionchat',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read_region_msgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov', 'avi', 'mkv', 'webm']), store.models.validate_video_duration]),
        ),
    ]
