# Generated by Django 4.2.23 on 2025-08-18 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
