# Generated by Django 4.2.23 on 2026-08-12 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_messageregionchat_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='store.story'),
        ),
    ]
