# Generated by Django 4.2.23 on 2026-08-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_privatemessage_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessagefile',
            name='is_listened',
            field=models.BooleanField(default=False),
        ),
    ]
