# Generated by Django 4.2.23 on 2026-08-15 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_privatemessagefile_is_listened'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessagefile',
            name='listened_by',
            field=models.ManyToManyField(blank=True, related_name='listened_group_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
