# Generated by Django 4.2.23 on 2026-08-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_groupmessagefile_listened_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagefile',
            name='is_listened',
            field=models.BooleanField(default=False),
        ),
    ]
