# Generated by Django 4.2.23 on 2026-08-15 14:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_messagefile_is_listened'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageregionfile',
            name='listened_by',
            field=models.ManyToManyField(blank=True, related_name='listened_region_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
