# Generated by Django 4.2.23 on 2025-09-10 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_messageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_imag_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='products/thumbs/'),
        ),
        migrations.AddField(
            model_name='product',
            name='main_image_webp',
            field=models.ImageField(blank=True, null=True, upload_to='product/webp'),
        ),
    ]
