# Generated by Django 4.2.23 on 2025-09-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_product_main_imag_thumb_product_main_image_webp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_imag_thumb',
            new_name='main_image_thumb',
        ),
    ]
