# Generated by Django 4.2.23 on 2026-08-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_story_options_story_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='stories/thumbnails/'),
        ),
    ]
