# Generated by Django 4.2.23 on 2025-10-02 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_rename_main_imag_thumb_product_main_image_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
