# Generated by Django 4.2.23 on 2026-08-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_storylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessage',
            name='call_duration',
            field=models.PositiveIntegerField(blank=True, help_text='Длительность звонка в секундах', null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='call_status',
            field=models.CharField(blank=True, choices=[('answered', 'Отвечен'), ('missed', 'Пропущен'), ('declined', 'Отклонен')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='privatemessage',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text or Media'), ('call', 'Call')], default='text', max_length=20),
        ),
    ]
