# Generated by Django 4.2.23 on 2025-10-05 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_product_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureproduct',
            old_name='valueFeatur',
            new_name='valueFeature',
        ),
    ]
