# Generated by Django 4.2.23 on 2026-08-30 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_privatemessage_call_duration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(help_text='Имя контакта в телефонной книге', max_length=255)),
                ('contact_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_by', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'contact_user')},
            },
        ),
    ]
