# Generated by Django 4.2.23 on 2025-10-07 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_featuretemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproduct',
            name='nameFeature',
        ),
        migrations.AddField(
            model_name='featureproduct',
            name='feature_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='store.featuretemplate'),
        ),
        migrations.AlterField(
            model_name='featureproduct',
            name='fk_Products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.product'),
        ),
    ]
