# Generated by Django 4.2.23 on 2025-10-08 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_featureproduct_namefeature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureproduct',
            name='feature_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='features', to='store.featuretemplate'),
        ),
    ]
