# Generated by Django 4.2.23 on 2025-10-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_featureproduct_feature_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featureproduct',
            old_name='fk_Products',
            new_name='product',
        ),
    ]
